"""AEC cross-MCP composite — aec_render_to_pdf_report.

Renders via blender-mcp / flux-mcp / svg-mcp, then compiles outputs into a
single branded PDF report with title page + page numbers + metadata.
"""

from __future__ import annotations

import logging
import os
from datetime import datetime
from pathlib import Path

from stirling_mcp.client import get_client
from stirling_mcp.config import SETTINGS
from stirling_mcp.app import mcp
from stirling_mcp.utils.mcp_client import call_mcp_tool, CrossMCPError

log = logging.getLogger("stirling_mcp.composites.aec.render_report")


@mcp.tool()
async def aec_render_to_pdf_report(
    title: str,
    image_paths: list[str] | None = None,
    flux_prompts: list[str] | None = None,
    flux_mcp_url: str | None = None,
    project: str = "",
    author: str = "",
) -> dict:
    """Combine generated/rendered images into a branded PDF report.

    Workflow:
        1. (Optional) call flux-mcp to generate images from prompts
        2. Combine with any pre-existing image_paths
        3. Render cover via Markdown→PDF
        4. Convert all images to PDF via Stirling's /convert/img/pdf
        5. Merge cover + images
        6. Add page numbers + metadata

    Args:
        title: report title (cover page header + PDF metadata)
        image_paths: paths to existing PNG/JPG files to include
        flux_prompts: text prompts; if set, calls flux-mcp to generate one
            image per prompt before assembling the report
        flux_mcp_url: override default endpoint (defaults to
            ``http://flux-mcp:8086/mcp/`` via env ``FLUX_MCP_URL``)
        project: optional project name (cover + metadata)
        author: optional author (cover + metadata)

    Returns: `{success, output_path, image_count, endpoints_chained}`
    """
    flux_endpoint = (
        flux_mcp_url
        or os.environ.get("FLUX_MCP_URL")
        or "http://flux-mcp:8086/mcp/"
    )

    client = get_client()
    chained: list[str] = []

    images: list[str] = list(image_paths or [])

    if flux_prompts:
        for prompt in flux_prompts:
            try:
                r = await call_mcp_tool(
                    flux_endpoint,
                    "generate_image",
                    {"prompt": prompt, "width": 1024, "height": 1024, "steps": 4},
                    timeout=180,
                )
                p = r.get("file_path") or r.get("path") or r.get("output_path")
                if p:
                    images.append(p)
            except CrossMCPError as e:
                log.warning("flux generation failed for prompt: %s — %s", prompt[:50], e)
        chained.append(f"flux-mcp:generate_image × {len(flux_prompts)}")

    if not images:
        return {"success": False, "error": "no images to assemble (provide image_paths or flux_prompts)"}

    # Cover sheet
    md = [
        f"# {title}",
        f"\n*{project}*" if project else "",
        f"\nBy: **{author}**" if author else "",
        f"\nDate: {datetime.utcnow():%Y-%m-%d}",
        f"\n\n**Images:** {len(images)}",
        "\n\n---\n*Generated by Stirling-PDF MCP aec_render_to_pdf_report*",
    ]
    md_path = SETTINGS.output_dir / f"render-report-{title[:20].replace(' ', '_')}.md"
    md_path.write_text("\n".join(md), encoding="utf-8")
    cover = await client.post_form(
        "/api/v1/convert/markdown/pdf",
        input_files=[md_path],
        output_name_hint="render-report-cover",
    )
    chained.append("markdown/pdf (cover)")
    cover_pdf = Path(cover["output_path"]) if cover.get("success") else None

    # Images → one PDF
    imgs_pdf = await client.post_form(
        "/api/v1/convert/img/pdf",
        input_files=[Path(p) for p in images],
        form_data={"stretch": False, "autoRotate": True, "colorType": "color"},
        output_name_hint="render-report-images",
    )
    chained.append("convert/img/pdf")
    if not imgs_pdf.get("success"):
        return {"success": False, "stage": "img/pdf", **imgs_pdf}
    imgs_pdf_path = Path(imgs_pdf["output_path"])

    # Merge
    pieces = []
    if cover_pdf:
        pieces.append(cover_pdf)
    pieces.append(imgs_pdf_path)
    merge = await client.post_form(
        "/api/v1/general/merge-pdfs",
        input_files=pieces,
        form_data={"sortType": "orderProvided"},
        output_name_hint="render-report-merged",
    )
    if not merge.get("success"):
        return {"success": False, "stage": "merge", **merge}
    work = Path(merge["output_path"])
    chained.append("merge-pdfs")

    # Page numbers + metadata
    nums = await client.post_form(
        "/api/v1/misc/add-page-numbers",
        input_files=[work],
        form_data={
            "position": 5,
            "startingNumber": 1,
            "pagesToNumber": "all",
            "customMargin": "small",
            "customText": "{n} / {total}",
            "fontSize": 10,
        },
        output_name_hint="render-report-numbered",
    )
    if nums.get("success"):
        work = Path(nums["output_path"])
        chained.append("add-page-numbers")

    meta = await client.post_form(
        "/api/v1/misc/update-metadata",
        input_files=[work],
        form_data={"title": title, "author": author, "subject": project, "creator": "stirling-pdf-mcp"},
        output_name_hint="render-report-meta",
    )
    if meta.get("success"):
        work = Path(meta["output_path"])
        chained.append("update-metadata")

    return {
        "success": True,
        "output_path": str(work),
        "image_count": len(images),
        "title": title,
        "endpoints_chained": chained,
    }
