"""AEC composite — aec_rfi_packet.

Generate an RFI (Request For Information) packet: template-fill cover sheet
+ referenced drawings + sequential numbering.
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path

from stirling_mcp.client import get_client
from stirling_mcp.config import SETTINGS
from stirling_mcp.app import mcp

log = logging.getLogger("stirling_mcp.composites.aec.rfi_packet")


@mcp.tool()
async def aec_rfi_packet(
    rfi_number: str,
    subject: str,
    question: str,
    project: str,
    requester: str,
    referenced_drawings: list[str] | None = None,
    response_required_by: str | None = None,
) -> dict:
    """Build an RFI packet PDF: cover + referenced drawings.

    Workflow:
        1. Render a Markdown cover sheet to PDF (project/RFI#/subject/
           question/requester/date/response-by)
        2. Append all referenced drawings
        3. Stamp every page with the RFI number

    Args:
        rfi_number: e.g. "RFI-2026-042"
        subject: short subject line
        question: the actual question text (Markdown supported)
        project: project name (goes in header)
        requester: who's asking
        referenced_drawings: list of PDF paths to append
        response_required_by: ISO date string

    Returns: `{success, output_path, page_count_estimate, endpoints_chained}`
    """
    client = get_client()
    chained: list[str] = []

    md = [
        f"# RFI {rfi_number}",
        f"\n**Project:** {project}",
        f"\n**Subject:** {subject}",
        f"\n**Requested by:** {requester}",
        f"\n**Date:** {datetime.utcnow():%Y-%m-%d}",
    ]
    if response_required_by:
        md.append(f"\n**Response required by:** {response_required_by}")
    md.append("\n\n## Question\n")
    md.append(question)
    if referenced_drawings:
        md.append("\n\n## Referenced drawings\n")
        for d in referenced_drawings:
            md.append(f"- {Path(d).name}")
    md.append("\n\n---\n\n*Generated by Stirling-PDF MCP aec_rfi_packet*\n")

    md_path = SETTINGS.output_dir / f"{rfi_number.replace('/', '-')}-cover.md"
    md_path.write_text("\n".join(md), encoding="utf-8")

    cover = await client.post_form(
        "/api/v1/convert/markdown/pdf",
        input_files=[md_path],
        output_name_hint=f"{rfi_number}-cover",
    )
    if not cover.get("success"):
        return {"success": False, "stage": "cover-render", **cover}
    work = Path(cover["output_path"])
    chained.append("markdown/pdf")

    if referenced_drawings:
        merge = await client.post_form(
            "/api/v1/general/merge-pdfs",
            input_files=[work, *(Path(p) for p in referenced_drawings)],
            form_data={"sortType": "orderProvided"},
            output_name_hint=f"{rfi_number}-merged",
        )
        if merge.get("success"):
            work = Path(merge["output_path"])
            chained.append("merge-pdfs")

    stamp = await client.post_form(
        "/api/v1/misc/add-page-numbers",
        input_files=[work],
        form_data={
            "position": 3,  # top-right
            "startingNumber": 1,
            "pagesToNumber": "all",
            "customMargin": "small",
            "customText": rfi_number + " — {n}",
            "fontSize": 9,
            "fontType": "Helvetica",
        },
        output_name_hint=f"{rfi_number}-stamped",
    )
    if stamp.get("success"):
        work = Path(stamp["output_path"])
        chained.append("add-page-numbers (rfi stamp)")

    return {
        "success": True,
        "output_path": str(work),
        "rfi_number": rfi_number,
        "drawing_count": len(referenced_drawings or []),
        "endpoints_chained": chained,
    }
