"""Auto-generated Stirling-PDF tool wrappers — category Convert.

Generated from the live Stirling OpenAPI spec. See ``scripts/gen_tools.py``.
"""

from __future__ import annotations

from stirling_mcp.client import get_client
from stirling_mcp.server import mcp

@mcp.tool()
async def convert_vector_pdf(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert PostScript formats to PDF
    
    Converts PostScript vector inputs (PS, EPS, EPSF) to PDF using Ghostscript. Input:PS/EPS Output:PDF Type:SISO
    
    Endpoint: ``POST /api/v1/convert/vector/pdf``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/vector/pdf',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_text_editor_pdf(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert Text Editor Format to PDF
    
    Rebuilds a PDF from the editable JSON structure generated by the text editor tool. Input:JSON Output:PDF Type:SISO
    
    Endpoint: ``POST /api/v1/convert/text-editor/pdf``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/text-editor/pdf',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_svg_pdf(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert SVG to PDF
    
    This endpoint converts one or more SVG (Scalable Vector Graphics) files to PDF format. Each SVG is converted to a separate PDF file. The conversion preserves vector graphics for crisp output at any resolution - no rasterization occurs. SVG dimensions (width/height) determine the PDF page size; defaults to A4 if not specified. SVG content is sanitized to prevent XSS attacks. Input: SVG file(s), Output: PDF file(s) or ZIP. Type: MIMO
    
    Endpoint: ``POST /api/v1/convert/svg/pdf``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/svg/pdf',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_pdf_xml(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert PDF to XML
    
    This endpoint converts a PDF file to an XML file. Input:PDF Output:XML Type:SISO
    
    Endpoint: ``POST /api/v1/convert/pdf/xml``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/pdf/xml',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_pdf_xlsx(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert a PDF to an Excel spreadsheet (XLSX)
    
    Extracts tabular data from each page of a PDF and writes it into an Excel workbook, one sheet per table. Input:PDF Output:XLSX Type:SISO
    
    Endpoint: ``POST /api/v1/convert/pdf/xlsx``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/pdf/xlsx',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_pdf_vector(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert PDF to vector format
    
    Converts PDF to Ghostscript vector formats (EPS, PS, PCL, or XPS). Input:PDF Output:VECTOR Type:SISO
    
    Endpoint: ``POST /api/v1/convert/pdf/vector``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/pdf/vector',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_pdf_text(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert PDF to Text or RTF format
    
    This endpoint converts a given PDF file to Text or RTF format. Input:PDF Output:TXT Type:SISO
    
    Endpoint: ``POST /api/v1/convert/pdf/text``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/pdf/text',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_pdf_text_editor(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert PDF to Text Editor Format
    
    Extracts PDF text, fonts, and metadata into an editable JSON structure for the text editor tool. Input:PDF Output:JSON Type:SISO
    
    Endpoint: ``POST /api/v1/convert/pdf/text-editor``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/pdf/text-editor',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_pdf_text_editor_partial_by(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Apply incremental edits from text editor to a cached PDF
    
    Applies edits for the specified pages of a cached PDF and returns an updated PDF. Requires the PDF to have been previously cached via the text editor metadata endpoint. The jobId must be obtained from the metadata extraction endpoint.
    
    Endpoint: ``POST /api/v1/convert/pdf/text-editor/partial/{jobId}``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/pdf/text-editor/partial/{jobId}',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_pdf_text_editor_metadata(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Extract PDF metadata for text editor lazy loading
    
    Extracts document metadata, fonts, and page dimensions for the text editor tool. Caches the document for subsequent page requests. Returns a server-generated jobId scoped to the authenticated user. Input:PDF Output:JSON Type:SISO
    
    Endpoint: ``POST /api/v1/convert/pdf/text-editor/metadata``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/pdf/text-editor/metadata',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_pdf_text_editor_clear_cache_by(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Clear cached PDF document for text editor
    
    Manually clears a cached PDF document used by the text editor to free up server resources. Called automatically after 30 minutes. The jobId must belong to the authenticated user.
    
    Endpoint: ``POST /api/v1/convert/pdf/text-editor/clear-cache/{jobId}``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/pdf/text-editor/clear-cache/{jobId}',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_pdf_presentation(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert PDF to Presentation format
    
    This endpoint converts a given PDF file to a Presentation format. Input:PDF Output:PPT Type:SISO
    
    Endpoint: ``POST /api/v1/convert/pdf/presentation``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/pdf/presentation',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_pdf_html(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert PDF to HTML
    
    This endpoint converts a PDF file to HTML format. Input:PDF Output:HTML Type:SISO
    
    Endpoint: ``POST /api/v1/convert/pdf/html``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/pdf/html',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_pdf_epub(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert PDF to EPUB/AZW3
    
    Convert a PDF file to a high-quality EPUB or AZW3 ebook using Calibre. Input:PDF Output:EPUB/AZW3 Type:SISO
    
    Endpoint: ``POST /api/v1/convert/pdf/epub``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/pdf/epub',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_pdf_cbz(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert PDF to CBZ comic book archive
    
    This endpoint converts a PDF file to a CBZ (ZIP) comic book archive. Input:PDF Output:CBZ Type:SISO
    
    Endpoint: ``POST /api/v1/convert/pdf/cbz``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/pdf/cbz',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_pdf_cbr(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert PDF to CBR comic book archive
    
    This endpoint converts a PDF file to a CBR comic book archive using the local RAR CLI. Input:PDF Output:CBR Type:SISO
    
    Endpoint: ``POST /api/v1/convert/pdf/cbr``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/pdf/cbr',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_eml_pdf(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert EML/MSG to PDF
    
    This endpoint converts EML (email) and MSG (Outlook) files to PDF format with extensive customization options. Features include font settings, image constraints, display modes, attachment handling, and HTML debug output. Input: EML or MSG file, Output: PDF or HTML file. Type: SISO
    
    Endpoint: ``POST /api/v1/convert/eml/pdf``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/eml/pdf',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_ebook_pdf(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert an eBook file to PDF
    
    This endpoint converts common eBook formats (EPUB, MOBI, AZW3, FB2, TXT, DOCX) to PDF using Calibre. Input:BOOK Output:PDF Type:SISO
    
    Endpoint: ``POST /api/v1/convert/ebook/pdf``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/ebook/pdf',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_cbz_pdf(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert CBZ comic book archive to PDF
    
    This endpoint converts a CBZ (ZIP) comic book archive to a PDF file. Input:CBZ Output:PDF Type:SISO
    
    Endpoint: ``POST /api/v1/convert/cbz/pdf``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/cbz/pdf',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_cbr_pdf(
    input_files: list[str] | None = None,
    form_data: dict | None = None,
) -> dict:
    """Convert CBR comic book archive to PDF
    
    This endpoint converts a CBR (RAR) comic book archive to a PDF file. Input:CBR Output:PDF Type:SISO
    
    Endpoint: ``POST /api/v1/convert/cbr/pdf``
    """
    from pathlib import Path
    return await get_client().post_form(
        '/api/v1/convert/cbr/pdf',
        input_files=[Path(p) for p in (input_files or [])],
        form_data=form_data or {},
    )


@mcp.tool()
async def convert_pdf_text_editor_page_by_by_get(jobId: str, pageNumber: str) -> dict:
    """Extract single page from cached PDF for text editor
    
    Retrieves a single page's content from a previously cached PDF document for the text editor tool. Requires prior call to /pdf/text-editor/metadata. The jobId must belong to the authenticated user. Output:JSON
    
    Endpoint: ``GET /api/v1/convert/pdf/text-editor/page/{jobId}/{pageNumber}``
    """
    return await get_client().get_json(f"/api/v1/convert/pdf/text-editor/page/{jobId}/{pageNumber}")


@mcp.tool()
async def convert_pdf_text_editor_fonts_by_by_get(jobId: str, pageNumber: str) -> dict:
    """Extract fonts used by a single cached page for text editor
    
    Retrieves the font payloads used by a single page from a previously cached PDF document. Requires prior call to /pdf/text-editor/metadata. The jobId must belong to the authenticated user. Output:JSON
    
    Endpoint: ``GET /api/v1/convert/pdf/text-editor/fonts/{jobId}/{pageNumber}``
    """
    return await get_client().get_json(f"/api/v1/convert/pdf/text-editor/fonts/{jobId}/{pageNumber}")

